"""models update

Revision ID: 64257087c57c
Revises: c760939ea619
Create Date: 2022-08-16 13:24:43.136088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64257087c57c'
down_revision = 'c760939ea619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.drop_constraint('shows_artist_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_venue_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'artist', ['artist_id'], ['id'])
    op.drop_column('shows', 'artist')
    op.drop_column('shows', 'venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_venue_fkey', 'shows', 'venue', ['venue'], ['id'])
    op.create_foreign_key('shows_artist_fkey', 'shows', 'artist', ['artist'], ['id'])
    op.drop_column('shows', 'artist_id')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
