"""area model

Revision ID: eea9ab1dc8ca
Revises: 64257087c57c
Create Date: 2022-08-16 21:36:28.177501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea9ab1dc8ca'
down_revision = '64257087c57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venue', sa.Column('area_id', sa.Integer(), nullable=True))
    op.alter_column('venue', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_foreign_key(None, 'venue', 'area', ['area_id'], ['id'])
    op.drop_column('venue', 'state')
    op.drop_column('venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.alter_column('venue', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('venue', 'area_id')
    op.drop_table('area')
    # ### end Alembic commands ###
